# Generated by Django 6.0.4 on 2026-04-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Material')),
                ('categoria', models.CharField(choices=[('ALIMENTOS', 'Alimentos não perecíveis'), ('VESTUARIO', 'Roupas e Calçados'), ('HIGIENE', 'Produtos de Higiene Pessoal'), ('EQUIPAMENTOS', 'Equipamentos (Cadeiras de rodas, muletas, etc)'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('estado', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Usado (Em bom estado)'), ('REPARO', 'Usado (Precisa de pequenos reparos)')], max_length=20, verbose_name='Estado de Conservação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
        ),
    ]
