# Generated by Django 6.0.4 on 2026-05-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='validade',
        ),
    ]
