# Generated by Django 6.0.4 on 2026-05-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0009_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
